// <auto-generated />
using System;
using MVCVoertuig.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCVoertuig.Migrations
{
    [DbContext(typeof(VoertuigDbContext))]
    partial class VoertuigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCVoertuig.Models.Data.Voertuig", b =>
                {
                    b.Property<int>("VoertuigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoertuigId"), 1L, 1);

                    b.Property<bool>("AanwezigInShowroom")
                        .HasColumnType("bit");

                    b.Property<int?>("Bouwjaar")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Km")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MerkType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("VerkoopPrijs")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("VoertuigId");

                    b.ToTable("Voertuigen");
                });
#pragma warning restore 612, 618
        }
    }
}
